# Generated by Django 3.2.7 on 2021-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210917_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='votes_to_skip',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
