# Generated by Django 3.2.7 on 2021-09-17 07:26

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210917_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=leads.models.generateCode, max_length=50, unique=True),
        ),
    ]
